version: '3.8'

services:
  postgres:
    container_name: my_postgres_container
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: narendra
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: ${DB_HOST_NAME}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  web:
    build: ./webapp
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: "http://localhost:3000"  # Use the service name of the backend service
    depends_on:
      - server

volumes:
  postgres_data:
